//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceivingManagementSystem.Android {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceivingManagementSystem.Android.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver{0}.
        /// </summary>
        public static string app_version_format {
            get {
                return ResourceManager.GetString("app_version_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Link Profile.
        /// </summary>
        public static string auto_link_profile {
            get {
                return ResourceManager.GetString("auto_link_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bkward Match.
        /// </summary>
        public static string backward_match {
            get {
                return ResourceManager.GetString("backward_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TID.
        /// </summary>
        public static string bank_tid {
            get {
                return ResourceManager.GetString("bank_tid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UII.
        /// </summary>
        public static string bank_uii {
            get {
                return ResourceManager.GetString("bank_uii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string bank_user {
            get {
                return ResourceManager.GetString("bank_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARCODE.
        /// </summary>
        public static string barcode_uppercase {
            get {
                return ResourceManager.GetString("barcode_uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer.
        /// </summary>
        public static string buzzer {
            get {
                return ResourceManager.GetString("buzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buzzer volume.
        /// </summary>
        public static string buzzer_volume {
            get {
                return ResourceManager.GetString("buzzer_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loud.
        /// </summary>
        public static string buzzer_volume_loud {
            get {
                return ResourceManager.GetString("buzzer_volume_loud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string buzzer_volume_low {
            get {
                return ResourceManager.GetString("buzzer_volume_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string buzzer_volume_middle {
            get {
                return ResourceManager.GetString("buzzer_volume_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string channel {
            get {
                return ResourceManager.GetString("channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch11.
        /// </summary>
        public static string channel11 {
            get {
                return ResourceManager.GetString("channel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch17.
        /// </summary>
        public static string channel17 {
            get {
                return ResourceManager.GetString("channel17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch23.
        /// </summary>
        public static string channel23 {
            get {
                return ResourceManager.GetString("channel23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch24.
        /// </summary>
        public static string channel24 {
            get {
                return ResourceManager.GetString("channel24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch25.
        /// </summary>
        public static string channel25 {
            get {
                return ResourceManager.GetString("channel25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch5.
        /// </summary>
        public static string channel5 {
            get {
                return ResourceManager.GetString("channel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to SP1.
        /// </summary>
        public static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error to SP1.
        /// </summary>
        public static string connection_error {
            get {
                return ResourceManager.GetString("connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to communicate data with SP1.
        /// </summary>
        public static string E_MSG_COMMUNICATION {
            get {
                return ResourceManager.GetString("E_MSG_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Pattern in hexadecimal.
        /// </summary>
        public static string E_MSG_FILTER_INVALID_PATTERN {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_INVALID_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Pattern in capital.
        /// </summary>
        public static string E_MSG_FILTER_NOT_CAPITAL {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_NOT_CAPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset can be entered from 0 to 524287.
        /// </summary>
        public static string E_MSG_FILTER_OUT_OF_RANGE_OFFSET {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_OUT_OF_RANGE_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern can input up to 256 bits.
        /// </summary>
        public static string E_MSG_FILTER_OUT_OF_RANGE_PATTERN {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_OUT_OF_RANGE_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range value is input..
        /// </summary>
        public static string E_MSG_LOCATION_TAG_RANGE {
            get {
                return ResourceManager.GetString("E_MSG_LOCATION_TAG_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save range setting..
        /// </summary>
        public static string E_MSG_LOCATION_TAG_SAVE_ERROR {
            get {
                return ResourceManager.GetString("E_MSG_LOCATION_TAG_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not connected to SP1.
        /// </summary>
        public static string E_MSG_NO_CONNECTION {
            get {
                return ResourceManager.GetString("E_MSG_NO_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting failed.
        /// </summary>
        public static string E_MSG_SAVE_SETTINGS {
            get {
                return ResourceManager.GetString("E_MSG_SAVE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter setting failed.
        /// </summary>
        public static string E_MSG_SET_FILTER {
            get {
                return ResourceManager.GetString("E_MSG_SET_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タグ読取停止中にエラーが発生しました。.
        /// </summary>
        public static string E_MSG_TAG {
            get {
                return ResourceManager.GetString("E_MSG_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all 1D codes.
        /// </summary>
        public static string enable_all_1d_codes {
            get {
                return ResourceManager.GetString("enable_all_1d_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all 2D codes.
        /// </summary>
        public static string enable_all_2d_codes {
            get {
                return ResourceManager.GetString("enable_all_2d_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Match.
        /// </summary>
        public static string forward_match {
            get {
                return ResourceManager.GetString("forward_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter setting cleared.
        /// </summary>
        public static string I_MSG_CLEAR_FILTER {
            get {
                return ResourceManager.GetString("I_MSG_CLEAR_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save range setting..
        /// </summary>
        public static string I_MSG_LOCATION_TAG_SETTING {
            get {
                return ResourceManager.GetString("I_MSG_LOCATION_TAG_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while settings are being applied.
        /// </summary>
        public static string I_MSG_PROGRESS_SETTING {
            get {
                return ResourceManager.GetString("I_MSG_PROGRESS_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings have been saved.
        /// </summary>
        public static string I_MSG_SAVE_SETTINGS {
            get {
                return ResourceManager.GetString("I_MSG_SAVE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter settings saved.
        /// </summary>
        public static string I_MSG_SET_FILTER {
            get {
                return ResourceManager.GetString("I_MSG_SET_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Profile.
        /// </summary>
        public static string link_profile {
            get {
                return ResourceManager.GetString("link_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string link_profile_1 {
            get {
                return ResourceManager.GetString("link_profile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string link_profile_4 {
            get {
                return ResourceManager.GetString("link_profile_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string link_profile_5 {
            get {
                return ResourceManager.GetString("link_profile_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocateTag.
        /// </summary>
        public static string locate_tag {
            get {
                return ResourceManager.GetString("locate_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; TOP.
        /// </summary>
        public static string navigate_up {
            get {
                return ResourceManager.GetString("navigate_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.
        /// </summary>
        public static string number_0_0 {
            get {
                return ResourceManager.GetString("number_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00.
        /// </summary>
        public static string number_0_00 {
            get {
                return ResourceManager.GetString("number_0_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset(bit).
        /// </summary>
        public static string offset_bit {
            get {
                return ResourceManager.GetString("offset_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        public static string pattern {
            get {
                return ResourceManager.GetString("pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs.
        /// </summary>
        public static string pcs {
            get {
                return ResourceManager.GetString("pcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polarization.
        /// </summary>
        public static string polarization {
            get {
                return ResourceManager.GetString("polarization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string polarization_both {
            get {
                return ResourceManager.GetString("polarization_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string polarization_horizontal {
            get {
                return ResourceManager.GetString("polarization_horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string polarization_vertical {
            get {
                return ResourceManager.GetString("polarization_vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power save.
        /// </summary>
        public static string power_save {
            get {
                return ResourceManager.GetString("power_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreFilters.
        /// </summary>
        public static string pre_filters {
            get {
                return ResourceManager.GetString("pre_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q factor.
        /// </summary>
        public static string q_factor {
            get {
                return ResourceManager.GetString("q_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string range_setting {
            get {
                return ResourceManager.GetString("range_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Settings.
        /// </summary>
        public static string range_setting_title {
            get {
                return ResourceManager.GetString("range_setting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapidRead.
        /// </summary>
        public static string rapid_read {
            get {
                return ResourceManager.GetString("rapid_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Power Level.
        /// </summary>
        public static string read_power_level {
            get {
                return ResourceManager.GetString("read_power_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dBm.
        /// </summary>
        public static string read_power_level_unit {
            get {
                return ResourceManager.GetString("read_power_level_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Tag:.
        /// </summary>
        public static string read_tag_head {
            get {
                return ResourceManager.GetString("read_tag_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti Re-read.
        /// </summary>
        public static string report_unique_tags {
            get {
                return ResourceManager.GetString("report_unique_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner version.
        /// </summary>
        public static string scanner_version {
            get {
                return ResourceManager.GetString("scanner_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string session {
            get {
                return ResourceManager.GetString("session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0.
        /// </summary>
        public static string session_s0 {
            get {
                return ResourceManager.GetString("session_s0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1.
        /// </summary>
        public static string session_s1 {
            get {
                return ResourceManager.GetString("session_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S2.
        /// </summary>
        public static string session_s2 {
            get {
                return ResourceManager.GetString("session_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3.
        /// </summary>
        public static string session_s3 {
            get {
                return ResourceManager.GetString("session_s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs/s.
        /// </summary>
        public static string tags_per_second_unit {
            get {
                return ResourceManager.GetString("tags_per_second_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UII.
        /// </summary>
        public static string text_search_tag_uii_head {
            get {
                return ResourceManager.GetString("text_search_tag_uii_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tags.
        /// </summary>
        public static string total_tags {
            get {
                return ResourceManager.GetString("total_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger mode.
        /// </summary>
        public static string trigger_mode {
            get {
                return ResourceManager.GetString("trigger_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate.
        /// </summary>
        public static string trigger_mode_alternate {
            get {
                return ResourceManager.GetString("trigger_mode_alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto off.
        /// </summary>
        public static string trigger_mode_auto_off {
            get {
                return ResourceManager.GetString("trigger_mode_auto_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string trigger_mode_continuous {
            get {
                return ResourceManager.GetString("trigger_mode_continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentary.
        /// </summary>
        public static string trigger_mode_momentary {
            get {
                return ResourceManager.GetString("trigger_mode_momentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger release.
        /// </summary>
        public static string trigger_mode_trigger_release {
            get {
                return ResourceManager.GetString("trigger_mode_trigger_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UII.
        /// </summary>
        public static string uii {
            get {
                return ResourceManager.GetString("uii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection .....
        /// </summary>
        public static string waiting_for_connection {
            get {
                return ResourceManager.GetString("waiting_for_connection", resourceCulture);
            }
        }
    }
}
