//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceivingManagementSystem.Android {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceivingManagementSystem.Android.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1500.
        /// </summary>
        internal static string locate_tag_initialize_time {
            get {
                return ResourceManager.GetString("locate_tag_initialize_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string locate_tag_read_power_levels_item0 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string locate_tag_read_power_levels_item1 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string locate_tag_read_power_levels_item2 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string locate_tag_read_power_levels_item3 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string read_power_level_on_search_tag {
            get {
                return ResourceManager.GetString("read_power_level_on_search_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -36.
        /// </summary>
        internal static string stage2_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage2_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -49.
        /// </summary>
        internal static string stage3_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage3_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -63.
        /// </summary>
        internal static string stage4_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage4_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -75.
        /// </summary>
        internal static string stage5_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage5_max_read_power_level_on_search", resourceCulture);
            }
        }
    }
}
