//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceivingManagementSystem {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceivingManagementSystem.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ver{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string app_version_format {
            get {
                return ResourceManager.GetString("app_version_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Link Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string auto_link_profile {
            get {
                return ResourceManager.GetString("auto_link_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bkward Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string backward_match {
            get {
                return ResourceManager.GetString("backward_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string bank_tid {
            get {
                return ResourceManager.GetString("bank_tid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UII に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string bank_uii {
            get {
                return ResourceManager.GetString("bank_uii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string bank_user {
            get {
                return ResourceManager.GetString("bank_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Barcode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BARCODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string barcode_uppercase {
            get {
                return ResourceManager.GetString("barcode_uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buzzer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buzzer {
            get {
                return ResourceManager.GetString("buzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buzzer volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buzzer_volume {
            get {
                return ResourceManager.GetString("buzzer_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loud に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buzzer_volume_loud {
            get {
                return ResourceManager.GetString("buzzer_volume_loud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buzzer_volume_low {
            get {
                return ResourceManager.GetString("buzzer_volume_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Middle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buzzer_volume_middle {
            get {
                return ResourceManager.GetString("buzzer_volume_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string channel {
            get {
                return ResourceManager.GetString("channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ch11 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string channel11 {
            get {
                return ResourceManager.GetString("channel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ch17 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string channel17 {
            get {
                return ResourceManager.GetString("channel17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ch23 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string channel23 {
            get {
                return ResourceManager.GetString("channel23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ch24 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string channel24 {
            get {
                return ResourceManager.GetString("channel24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ch25 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string channel25 {
            get {
                return ResourceManager.GetString("channel25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ch5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string channel5 {
            get {
                return ResourceManager.GetString("channel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected to SP1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection error to SP1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string connection_error {
            get {
                return ResourceManager.GetString("connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to communicate data with SP1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_COMMUNICATION {
            get {
                return ResourceManager.GetString("E_MSG_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter Pattern in hexadecimal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_FILTER_INVALID_PATTERN {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_INVALID_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter Pattern in capital に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_FILTER_NOT_CAPITAL {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_NOT_CAPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset can be entered from 0 to 524287 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_FILTER_OUT_OF_RANGE_OFFSET {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_OUT_OF_RANGE_OFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern can input up to 256 bits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_FILTER_OUT_OF_RANGE_PATTERN {
            get {
                return ResourceManager.GetString("E_MSG_FILTER_OUT_OF_RANGE_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid range value is input. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_LOCATION_TAG_RANGE {
            get {
                return ResourceManager.GetString("E_MSG_LOCATION_TAG_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save range setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_LOCATION_TAG_SAVE_ERROR {
            get {
                return ResourceManager.GetString("E_MSG_LOCATION_TAG_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not connected to SP1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_NO_CONNECTION {
            get {
                return ResourceManager.GetString("E_MSG_NO_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_SAVE_SETTINGS {
            get {
                return ResourceManager.GetString("E_MSG_SAVE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter setting failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_SET_FILTER {
            get {
                return ResourceManager.GetString("E_MSG_SET_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ読取停止中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string E_MSG_TAG {
            get {
                return ResourceManager.GetString("E_MSG_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable all 1D codes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enable_all_1d_codes {
            get {
                return ResourceManager.GetString("enable_all_1d_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable all 2D codes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enable_all_2d_codes {
            get {
                return ResourceManager.GetString("enable_all_2d_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string forward_match {
            get {
                return ResourceManager.GetString("forward_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter setting cleared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I_MSG_CLEAR_FILTER {
            get {
                return ResourceManager.GetString("I_MSG_CLEAR_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save range setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I_MSG_LOCATION_TAG_SETTING {
            get {
                return ResourceManager.GetString("I_MSG_LOCATION_TAG_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait while settings are being applied に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I_MSG_PROGRESS_SETTING {
            get {
                return ResourceManager.GetString("I_MSG_PROGRESS_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your settings have been saved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I_MSG_SAVE_SETTINGS {
            get {
                return ResourceManager.GetString("I_MSG_SAVE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter settings saved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string I_MSG_SET_FILTER {
            get {
                return ResourceManager.GetString("I_MSG_SET_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string link_profile {
            get {
                return ResourceManager.GetString("link_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string link_profile_1 {
            get {
                return ResourceManager.GetString("link_profile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string link_profile_4 {
            get {
                return ResourceManager.GetString("link_profile_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string link_profile_5 {
            get {
                return ResourceManager.GetString("link_profile_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LocateTag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string locate_tag {
            get {
                return ResourceManager.GetString("locate_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt; TOP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string navigate_up {
            get {
                return ResourceManager.GetString("navigate_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string number_0_0 {
            get {
                return ResourceManager.GetString("number_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0.00 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string number_0_00 {
            get {
                return ResourceManager.GetString("number_0_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset(bit) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string offset_bit {
            get {
                return ResourceManager.GetString("offset_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pattern {
            get {
                return ResourceManager.GetString("pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pcs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pcs {
            get {
                return ResourceManager.GetString("pcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polarization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string polarization {
            get {
                return ResourceManager.GetString("polarization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string polarization_both {
            get {
                return ResourceManager.GetString("polarization_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string polarization_horizontal {
            get {
                return ResourceManager.GetString("polarization_horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   V に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string polarization_vertical {
            get {
                return ResourceManager.GetString("polarization_vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string power_save {
            get {
                return ResourceManager.GetString("power_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PreFilters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pre_filters {
            get {
                return ResourceManager.GetString("pre_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q factor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string q_factor {
            get {
                return ResourceManager.GetString("q_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Range に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string range_setting {
            get {
                return ResourceManager.GetString("range_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Range Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string range_setting_title {
            get {
                return ResourceManager.GetString("range_setting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RapidRead に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string rapid_read {
            get {
                return ResourceManager.GetString("rapid_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Power Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string read_power_level {
            get {
                return ResourceManager.GetString("read_power_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dBm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string read_power_level_unit {
            get {
                return ResourceManager.GetString("read_power_level_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Tag: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string read_tag_head {
            get {
                return ResourceManager.GetString("read_tag_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anti Re-read に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string report_unique_tags {
            get {
                return ResourceManager.GetString("report_unique_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanner version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string scanner_version {
            get {
                return ResourceManager.GetString("scanner_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Session に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string session {
            get {
                return ResourceManager.GetString("session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string session_s0 {
            get {
                return ResourceManager.GetString("session_s0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string session_s1 {
            get {
                return ResourceManager.GetString("session_s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string session_s2 {
            get {
                return ResourceManager.GetString("session_s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string session_s3 {
            get {
                return ResourceManager.GetString("session_s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pcs/s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tags_per_second_unit {
            get {
                return ResourceManager.GetString("tags_per_second_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UII に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string text_search_tag_uii_head {
            get {
                return ResourceManager.GetString("text_search_tag_uii_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string total_tags {
            get {
                return ResourceManager.GetString("total_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trigger mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string trigger_mode {
            get {
                return ResourceManager.GetString("trigger_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alternate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string trigger_mode_alternate {
            get {
                return ResourceManager.GetString("trigger_mode_alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string trigger_mode_auto_off {
            get {
                return ResourceManager.GetString("trigger_mode_auto_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continuous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string trigger_mode_continuous {
            get {
                return ResourceManager.GetString("trigger_mode_continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Momentary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string trigger_mode_momentary {
            get {
                return ResourceManager.GetString("trigger_mode_momentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trigger release に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string trigger_mode_trigger_release {
            get {
                return ResourceManager.GetString("trigger_mode_trigger_release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UII に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string uii {
            get {
                return ResourceManager.GetString("uii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for connection .... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string waiting_for_connection {
            get {
                return ResourceManager.GetString("waiting_for_connection", resourceCulture);
            }
        }
    }
}
