//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceivingManagementSystem
{
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceivingManagementSystem.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   1500 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string locate_tag_initialize_time {
            get {
                return ResourceManager.GetString("locate_tag_initialize_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string locate_tag_read_power_levels_item0 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string locate_tag_read_power_levels_item1 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   15 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string locate_tag_read_power_levels_item2 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string locate_tag_read_power_levels_item3 {
            get {
                return ResourceManager.GetString("locate_tag_read_power_levels_item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string read_power_level_on_search_tag {
            get {
                return ResourceManager.GetString("read_power_level_on_search_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -36 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stage2_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage2_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -49 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stage3_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage3_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -63 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stage4_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage4_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -75 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stage5_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("stage5_max_read_power_level_on_search", resourceCulture);
            }
        }
    }
}
