//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceivingManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Preferences {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Preferences() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReceivingManagementSystem.Preferences", typeof(Preferences).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref_filter_bank.
        /// </summary>
        internal static string pref_filter_bank {
            get {
                return ResourceManager.GetString("pref_filter_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref_filter_offset.
        /// </summary>
        internal static string pref_filter_offset {
            get {
                return ResourceManager.GetString("pref_filter_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref_filter_pattern.
        /// </summary>
        internal static string pref_filter_pattern {
            get {
                return ResourceManager.GetString("pref_filter_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref_stage2_max_read_power_level_on_search.
        /// </summary>
        internal static string pref_stage2_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("pref_stage2_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref_stage3_max_read_power_level_on_search.
        /// </summary>
        internal static string pref_stage3_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("pref_stage3_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref_stage4_max_read_power_level_on_search.
        /// </summary>
        internal static string pref_stage4_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("pref_stage4_max_read_power_level_on_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref_stage5_max_read_power_level_on_search.
        /// </summary>
        internal static string pref_stage5_max_read_power_level_on_search {
            get {
                return ResourceManager.GetString("pref_stage5_max_read_power_level_on_search", resourceCulture);
            }
        }
    }
}
